1. Создайте двумерный массив 10x3, заполненный случайными значениями. В каждой строке выберите значение, наиболее близкое к 0.5.

2. Создайте двумерный массив 6x6, заполненный случайными значениями. Затем сумму по каждой строке поделите на минимальный элемент из столбца с тем же индексом.

3. На примере массива x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) найдите максимальный элемент в массиве среди элементов, перед которыми стоит ноль.

4. Пусть заданы два массива x = np.ones(10) и i = np.array([0, 1, 2, 3, 5, 5, 5, 8]). Прибавьте единицу к тем элементам массива x, индексы которых указаны в массиве i. В случае, если некоторый индекс встретился в массиве i несколько раз, прибавьте к соответствующему элементу массива x число вхождений данного индекса в массив i.

5. По заданному двумерному массиву размера NxN постройте словарь, ключи которого - индексы диагоналей, параллельных побочной (нумерация начинается с 0), а значения - списки элементов исходного массива, лежащих на соответствующих диагоналях. Решите задачу на примере массива a = np.arange(16).reshape(4, 4), в результате должен получиться словарь {0: [0], 1: [1, 4], 2: [2, 5, 8], 3: [3, 6, 9, 12], 4: [7, 10, 13], 5: [11, 14], 6: [15]}.

6. Написать функцию, реализующую алгоритм k-means. Входные и выходные значения функции должны быть аналогичны https://docs.scipy.org/doc/scipy-0.15.1/reference/generated/scipy.cluster.vq.kmeans.html. Функция должна содержать только один цикл while (for).

Exercise 1.

Создайте двумерный массив 10x3, заполненный случайными значениями. В каждой строке выберите значение, наиболее близкое к 0.5.

In [16]:
import numpy as np
a= np.random.random((10, 3))
b = np.argmin(np.abs(a - 0.5) , axis=1, out=None)
print(a)
for i in range (0, 10):
    print(a[i][b[i]])

[[ 0.7210242   0.53170955  0.72597421]
 [ 0.67344737  0.20005127  0.30722662]
 [ 0.3776275   0.88063019  0.96444288]
 [ 0.3270366   0.17020221  0.36039335]
 [ 0.52941073  0.72638236  0.28224588]
 [ 0.52500641  0.3711255   0.34492755]
 [ 0.37549911  0.29379884  0.05093186]
 [ 0.24636973  0.95567491  0.14086831]
 [ 0.75627867  0.33736264  0.9802932 ]
 [ 0.7544765   0.97229538  0.27574654]]
0.53170955232
0.673447367589
0.377627499074
0.360393346169
0.529410727271
0.525006413219
0.375499106893
0.246369729262
0.337362636035
0.275746537635


Exercise 2.

Создайте двумерный массив 6x6, заполненный случайными значениями. Затем сумму по каждой строке поделите на минимальный элемент из столбца с тем же индексом.

In [22]:
a= np.random.random((6, 6))
print(a, '\n')
print(np.sum(a, axis = 1)/np.min(a, axis = 0))


[[ 0.38396969  0.83659223  0.60416675  0.43229205  0.69788151  0.32093147]
 [ 0.86499392  0.25656456  0.93439564  0.05814055  0.55883052  0.0576297 ]
 [ 0.69245441  0.15161126  0.68735518  0.67860198  0.98511604  0.2406095 ]
 [ 0.93293078  0.31803228  0.53180496  0.62075648  0.52963301  0.47133801]
 [ 0.31818903  0.32950759  0.08792914  0.08453264  0.09255285  0.4489972 ]
 [ 0.07017973  0.26075833  0.91841364  0.7003194   0.37926791  0.98934407]] 

[ 46.67777865  18.01023763  39.07406096  58.5562965   14.71276632
  57.57939357]


Exercise 3.

На примере массива x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) найдите максимальный элемент в массиве среди элементов, перед которыми стоит ноль.

In [10]:
import numpy as np
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])


print (   np.max( x[(np.argwhere(x == 0) if( not((x.size-1) in np.argwhere(x == 0))) else np.argwhere(x == 0)[np.argwhere(x == 0)!=(x.size-1)])   +   1]  )  )


5


Exercise 4.

Пусть заданы два массива x = np.ones(10) и i = np.array([0, 1, 2, 3, 5, 5, 5, 8]). Прибавьте единицу к тем элементам массива x, индексы которых указаны в массиве i. В случае, если некоторый индекс встретился в массиве i несколько раз, прибавьте к соответствующему элементу массива x число вхождений данного индекса в массив i.

In [39]:
x = np.ones(10)
i = np.array([0, 1, 2, 3, 5, 5, 5, 8])
a, b = np.unique(i, return_counts=True)
for i in range(0, a.size):
    x[a[i]]+=b[i]
    

print(a)
print(b)
print(x)

#можно сделать без цикла, еще не придумал как


[0 1 2 3 5 8]
[1 1 1 1 3 1]
[ 2.  2.  2.  2.  1.  4.  1.  1.  2.  1.]


Exercise 5.

По заданному двумерному массиву размера NxN постройте словарь, ключи которого - индексы диагоналей, параллельных побочной (нумерация начинается с 0), а значения - списки элементов исходного массива, лежащих на соответствующих диагоналях. Решите задачу на примере массива a = np.arange(16).reshape(4, 4), в результате должен получиться словарь {0: [0], 1: [1, 4], 2: [2, 5, 8], 3: [3, 6, 9, 12], 4: [7, 10, 13], 5: [11, 14], 6: [15]}.

In [1]:

# a = np.arange(16).reshape(4, 4)
    
print(np.indices((8, 8)).sum(axis = 0) % 2)

NameError: name 'np' is not defined